dataset:
  train:
    name: mixed
    prob_ls: [0.33, 0.33, 0.33]
    dataset_list: 
    - name: deroll
      disp_name: heli_1
      dir: helicopter.tar
      filenames: data_split/helicopters/helicopter_split/helicopter_split_train.txt

    - name: deroll
      disp_name: heli_2
      dir: helicopter_2.tar
      filenames: data_split/helicopters/helicopter_2_split/helicopter_2_split_train.txt
    
    - name: deroll
      disp_name: fighter_heli
      dir: fighter_helicopter.tar
      filenames: data_split/helicopters/fighter_helicopter_split/fighter_helicopter_split_train.txt

      
          
